version: '3.8'
services:
  api_server:
    container_name: api_server
    build:
      context: ./packages/api_server
    ports:
      - '9000:9000'
    env_file: ./packages/api_server/.env
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:alpine
    volumes:
      - ./packages/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    # volumes:
    # - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
